### ISSUE TITLE
Problem with Xamarin

### ISSUE THREAD

**Issue by carmas123** [OpenSoftwareSolutions/PDFReporter#2]
Hi, I try to use PDFReporter with Xamarin, now I have binded JAR but I've a problem when try to export report:

09-14 11:23:59.030 I/MonoDroid(17362): java.lang.NullPointerException: Attempt to invoke interface method 'void org.oss.pdfreporter.xml.parsers.factory.IXmlParserFactory.setNamespaceAware(boolean)' on a null object reference
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.uses.org.apache.digester.impl.Digester.setNamespaceAware(Digester.java:338)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.uses.org.apache.digester.DelegatingAbstractDigester.setNamespaceAware(DelegatingAbstractDigester.java:71)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.engine.xml.JRXmlDigesterFactory.configureDigester(JRXmlDigesterFactory.java:115)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.engine.xml.JRXmlDigesterFactory.createDigester(JRXmlDigesterFactory.java:1315)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.engine.xml.JRXmlLoader.load(JRXmlLoader.java:208)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.PdfReporter.loadReport(PdfReporter.java:315)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.PdfReporter.exportFromXml(PdfReporter.java:163)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.PdfReporter.exportWithoutDataSource(PdfReporter.java:95)
09-14 11:23:59.030 I/MonoDroid(17362):  at org.oss.pdfreporter.PdfReporter.exportPdf(PdfReporter.java:156)
09-14 11:23:59.030 I/MonoDroid(17362):  at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
09-14 11:23:59.030 I/MonoDroid(17362):  at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:29)
09-14 11:23:59.030 I/MonoDroid(17362):  at android.view.View.performClick(View.java:5217)
09-14 11:23:59.030 I/MonoDroid(17362):  at android.view.View$PerformClick.run(View.java:20983)
09-14 11:23:59.030 I/MonoDroid(17362):  at android.os.Handler.handleCallback(Handler.java:739)
09-14 11:23:59.035 I/MonoDroid(17362):  at android.os.Handler.dispatchMessage(Handler.java:95)
09-14 11:23:59.035 I/MonoDroid(17362):  at android.os.Looper.loop(Looper.java:145)
09-14 11:23:59.035 I/MonoDroid(17362):  at android.app.ActivityThread.main(ActivityThread.java:6117)
09-14 11:23:59.035 I/MonoDroid(17362):  at java.lang.reflect.Method.invoke(Native Method)
09-14 11:23:59.035 I/MonoDroid(17362):  at java.lang.reflect.Method.invoke(Method.java:372)
09-14 11:23:59.035 I/MonoDroid(17362):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
09-14 11:23:59.035 I/MonoDroid(17362):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)

can anyone help me please?

**Comment by carmas123** [comment]
I see another related problem...
If I try to invoke 
FactoryManager.RegisterFactories();

I got this exception:

09-14 19:29:54.498 I/MonoDroid(17776): java.lang.NullPointerException
09-14 19:29:54.498 I/MonoDroid(17776):  at org.oss.pdfreporter.font.AbstractFontFactory.setSession(AbstractFontFactory.java:27)
09-14 19:29:54.498 I/MonoDroid(17776):  at org.oss.pdfreporter.registry.ApiRegistry.setSession(ApiRegistry.java:47)
09-14 19:29:54.498 I/MonoDroid(17776):  at org.oss.pdfreporter.registry.ApiRegistry.register(ApiRegistry.java:99)
09-14 19:29:54.498 I/MonoDroid(17776):  at org.oss.pdfreporter.font.FontFactory.registerFactory(FontFactory.java:19)
09-14 19:29:54.498 I/MonoDroid(17776):  at org.oss.pdfreporter.factory.FactoryManager.registerFactories(FactoryManager.java:37)
09-14 19:29:54.498 I/MonoDroid(17776):  at mono.android.view.View_OnClickListenerImplementor.n_onClick(Native Method)
09-14 19:29:54.498 I/MonoDroid(17776):  at mono.android.view.View_OnClickListenerImplementor.onClick(View_OnClickListenerImplementor.java:29)
09-14 19:29:54.498 I/MonoDroid(17776):  at android.view.View.performClick(View.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at android.view.View$PerformClick.run(View.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at android.os.Handler.handleCallback(Handler.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at android.os.Handler.dispatchMessage(Handler.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at android.os.Looper.loop(Looper.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at android.app.ActivityThread.main(ActivityThread.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at java.lang.reflect.Method.invokeNative(Native Method)
09-14 19:29:54.498 I/MonoDroid(17776):  at java.lang.reflect.Method.invoke(Method.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java)
09-14 19:29:54.498 I/MonoDroid(17776):  at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:132)
09-14 19:29:54.498 I/MonoDroid(17776):  at dalvik.system.NativeStart.main(Native Method)
